# .github/workflows/link-check.yml
name: Link Checker

on:
  push:
    paths:
      - 'docs/**'
      - 'scripts/check_links.py'
  pull_request:
    paths:
      - 'docs/**'
      - 'scripts/check_links.py'

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run broken‑link checker
        run: python scripts/check_links.py
